language: node_js

node_js:
 - node

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

defaults: &defaults
  script:
    - $(npm bin)/print-env TRAVIS
    - npm run start:ci &
    - npm run cy:run -- --record --parallel --group $STAGE_NAME
    - kill $(jobs -p) || true
